import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# 🔑 API Keys
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

# 📁 Directory & File Paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, "data")

# Ensure data directory exists
os.makedirs(DATA_DIR, exist_ok=True)

# Point directly to the JSON file generated by your crawler
RAW_DATA_FILE = os.path.join(BASE_DIR, "website_data.json")

# Path where FAISS will save the vector database
VECTOR_DB_PATH = os.path.join(DATA_DIR, "faiss_index")

# 🧠 AI Models
EMBEDDING_MODEL = "BAAI/bge-large-en-v1.5"
LLM_MODEL = "gemini-2.5-flash"
TEMPERATURE = 0.1

# ✂️ Text Chunking Parameters
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200